services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - ./sample.env:/app/.env
      - ./db/migrations:/app/db/migrations
    ports:
      - "8000:8000"
    env_file:
     - ./sample.env
    depends_on:
      - hich-db
      - redis

  hich-db:
    image: "postgres"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hich_db
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - hich-db:/var/lib/postgresql/data
  
  redis:
    image: "redis:6.2.2"
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  hich-db:
