services:
  #http-srv:
    #build:
      #context: .
    #restart: always
    #volumes:
      #- ./sample.env:/app/.env
    #ports:
      #- "8000:8000"
    #env_file:
     #- ./sample.env
    #depends_on:
      #- hich-db
      #- redis

  hich-db:
    image: "postgres"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hich_db
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - hich-db:/var/lib/postgresql/data
  
  redis:
    image: "redis:6.2.2"
    ports:
      - "6379:6379"

  #kafka0:
    ##image: confluentinc/cp-kafka:7.2.1.arm64
    #image: confluentinc/cp-kafka:7.2.1.amd64
    #hostname: kafka0
    #container_name: kafka0
    #ports:
      #- 9092:9092
      #- 9997:9997
    #environment:
      #KAFKA_BROKER_ID: 1
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      ##KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://kafka0:9092
      #KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      #KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      #KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      #KAFKA_PROCESS_ROLES: 'broker,controller'
      #KAFKA_NODE_ID: 1
      #KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka0:29093'
      #KAFKA_LISTENERS: 'PLAINTEXT://kafka0:29092,CONTROLLER://kafka0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      #KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      #KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      #KAFKA_JMX_PORT: 9997
      #KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997
    #volumes:
      #- ./update_run.sh:/tmp/update_run.sh
    #command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"



volumes:
  hich-db:
