// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForCreateOption implements pgx.CopyFromSource.
type iteratorForCreateOption struct {
	rows                 []CreateOptionParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateOption) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateOption) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PollID,
		r.rows[0].Content,
	}, nil
}

func (r iteratorForCreateOption) Err() error {
	return nil
}

func (q *Queries) CreateOption(ctx context.Context, db DBTX, arg []CreateOptionParams) (int64, error) {
	return db.CopyFrom(ctx, []string{"options"}, []string{"poll_id", "content"}, &iteratorForCreateOption{rows: arg})
}

// iteratorForCreatePollTag implements pgx.CopyFromSource.
type iteratorForCreatePollTag struct {
	rows                 []CreatePollTagParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePollTag) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePollTag) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PollID,
		r.rows[0].TagID,
	}, nil
}

func (r iteratorForCreatePollTag) Err() error {
	return nil
}

func (q *Queries) CreatePollTag(ctx context.Context, db DBTX, arg []CreatePollTagParams) (int64, error) {
	return db.CopyFrom(ctx, []string{"poll_tags"}, []string{"poll_id", "tag_id"}, &iteratorForCreatePollTag{rows: arg})
}
