// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Option struct {
	ID      int64
	PollID  int64
	Content string
	Counts  int32
}

type Poll struct {
	ID        int64
	Title     string
	CreatedAt pgtype.Timestamptz
}

type PollTag struct {
	PollID int64
	TagID  int64
}

type Tag struct {
	ID   int64
	Name string
}

type Vote struct {
	ID        int64
	PollID    int64
	OptionID  pgtype.Int8
	UserID    int64
	IsSkipped bool
	CreatedAt pgtype.Timestamptz
}
